# version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_USER: postgres
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
  
  graphql-engine:
    image: hasura/graphql-engine:v2.27.0
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/tasks_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/tasks_db
    depends_on:
      - postgres
  
  # Сервис для инициализации базы данных при первом запуске
  hasura-init:
    image: postgres:13
    depends_on:
      - postgres
      - graphql-engine
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./init-hasura.sh:/init-hasura.sh
    command: ["sh", "/init-hasura.sh"]
    restart: "no"

volumes:
  db_data: 